---
bchn_user: "{{ lookup('env', 'VAULT_DEPLOY_USER') }}"

# Chipnet (Testnet)
bchn_chipnet_data_dir: "/home/{{ bchn_user }}/.bitcoin/chipnet"
bchn_chipnet_config_file: "{{ bchn_chipnet_data_dir }}/bitcoin.conf"
bchn_chipnet_service_name: "bitcoind-chipnet"

chipnet_config:
  server: 1
  rpcuser: "bitcoin"
  rpcpassword: "{{ lookup('env', 'VAULT_RPC_PASSWORD') }}"
  rpcport: 48332
  p2pport: 48333
  onionport: 48334
  zmqpubrawblock: "tcp://127.0.0.1:28332"
  zmqpubrawtx: "tcp://127.0.0.1:28333"

# Mainnet
bchn_mainnet_data_dir: "/home/{{ bchn_user }}/.bitcoin/mainnet"
bchn_mainnet_config_file: "{{ bchn_mainnet_data_dir }}/bitcoin.conf"
bchn_mainnet_service_name: "bitcoind-mainnet"

mainnet_config:
  server: 1
  rpcuser: "bitcoin"
  rpcpassword: >-
    {{ lookup('env', 'VAULT_RPC_PASSWORD_MAINNET')
       | default(lookup('env', 'VAULT_RPC_PASSWORD')) }}
  rpcport: 8332
  p2pport: 8333
  onionport: 8334
  zmqpubrawblock: "tcp://127.0.0.1:18332" # Shifted for uniqueness
  zmqpubrawtx: "tcp://127.0.0.1:18333" # Shifted for uniqueness
