---
all:
  hosts:
    vps:
      ansible_host: "{{ lookup('env', 'VAULT_SERVER_IP') }}"
      ansible_user: "{{ lookup('env', 'VAULT_DEPLOY_USER') }}"
      ansible_python_interpreter: /usr/bin/python3
